/* AnoniPRO — textos de la interfaz en español e inglés.
 *
 * Una sola aplicación bilingüe: aquí están TODOS los textos visibles. Para
 * añadir un idioma nuevo basta con copiar el bloque y traducirlo; no hay que
 * tocar el resto del programa.
 *
 * Los nombres y descripciones de las categorías NO están aquí: los envía el
 * servidor (backend/app/detection/categorias.py) en los dos idiomas, para que
 * el catálogo tenga una sola fuente de verdad.
 */

const TEXTOS = {
  es: {
    // ── Cabecera y pie ──────────────────────────────────────────────────
    "app.titulo_pagina": "AnoniPRO — Anonimización local de documentos",
    "app.subtitulo": "Anonimización local de documentos — ningún dato sale de tu equipo",
    "app.pie": "Procesamiento 100 % local · Sin conexión a internet · Los documentos nunca se guardan en disco",
    "app.autor": "Autor: Dr. José Ramón Alberto Alonso",
    "cabecera.detector": "Modelo de detección de nombres",
    "cabecera.ocr": "Estado del OCR",
    "cabecera.tema": "Cambiar entre modo claro y oscuro",
    "cabecera.idioma": "Switch to English",

    // ── Acceso ──────────────────────────────────────────────────────────
    "login.instruccion": "Introduce la contraseña de acceso.",
    "login.password": "Contraseña",
    "login.entrar": "Entrar",
    "login.error": "Contraseña incorrecta.",

    // ── Panel de ajustes ────────────────────────────────────────────────
    "panel.perfil": "Perfil",
    "panel.guardar_perfil": "Guardar la configuración actual como perfil",
    "panel.que_se_detecta": "Qué se detecta y redacta",
    "panel.lista_negra": "Redactar siempre estos términos",
    "panel.lista_negra_ayuda": "Escribe aquí lo que quieras quitar y no se detecte solo (un apodo, una finca, un código…). Una casilla por término.",
    "panel.lista_blanca": "No redactar nunca estos términos",
    "panel.lista_blanca_ayuda": "Palabras que quieres respetar aunque se parezcan a datos personales (p. ej. un fármaco). Si la palabra sale «pegada» dentro de una detección mayor, se recorta de ella.",
    "panel.anadir_casilla": "＋ Añadir otra casilla",
    "panel.termino_ph": "Escribe un término…",
    "panel.quitar_casilla": "Quitar esta casilla",
    "panel.fechas_edad": "Fechas y edad",
    "panel.fechas": "Fechas del documento",
    "panel.fechas_ayuda": "«Desplazar» mueve todas las fechas el mismo número aleatorio de días: se conserva el orden y los intervalos entre ellas sin revelar las fechas reales.",
    "panel.fechas_tachar": "Tachar (redactar)",
    "panel.fechas_desplazar": "Desplazar (conserva la cronología)",
    "panel.edad": "Edad exacta",
    "panel.edad_ayuda": "«Rango etario» sustituye la edad exacta por su banda: «47 años» pasa a «45-49 años». La fecha de nacimiento se tacha siempre.",
    "panel.edad_tachar": "Tachar (redactar)",
    "panel.edad_rango": "Sustituir por rango etario (45-49 años)",
    "panel.ia": "Detección avanzada (IA local)",
    "panel.ia_ayuda": "Opcional. Usa un modelo de IA que corre en tu red para cazar datos que las reglas no ven. Funciona todo sin esto.",
    "panel.comprobar_equipo": "🖥️ Comprobar mi equipo",
    "panel.ajustes_ia": "⚙️ Ajustes de IA",
    "panel.reanalizar": "🔄 Volver a analizar con estos ajustes",
    "panel.perfil_propio": "— ajustes propios —",
    "panel.perfil_nombre": "Nombre del perfil (la configuración actual de interruptores):",

    // ── Zona de subida ──────────────────────────────────────────────────
    "subir.arrastra": "Arrastra aquí un documento",
    "subir.o": "o",
    "subir.elegir": "Elegir archivo…",
    "subir.formatos": "PDF (con texto o escaneado), Word (.docx) o imagen (JPG, PNG, TIFF)",
    "subir.ocr_nota": "Los escaneados e imágenes se leen con OCR en este mismo equipo.",
    "subir.ttl": "El documento se procesa solo aquí y se borra de la memoria a los {min} minutos.",
    "subir.analizando": "Analizando «{nombre}»…",
    "subir.en_cola": " ({n} en cola)",
    "subir.ocr_lento": "\nSi está escaneado, el OCR puede tardar en documentos largos.",
    "subir.reanalizando": "Volviendo a analizar…",
    "subir.formato_no": "Formato no compatible. Usa PDF, Word (.docx) o una imagen (JPG, PNG, TIFF).",
    "subir.error": "No se pudo procesar el documento:\n\n",
    "subir.caducado": "El documento caducó en memoria. Vuelve a subirlo.",
    "subir.quedan": "  ·  quedan {n} en cola",

    // ── Documento y detecciones ─────────────────────────────────────────
    "doc.zona_manual": "✏️ Marcar zona a mano",
    "doc.zona_manual_ayuda": "Dibujar un rectángulo sobre el documento para redactarlo (solo PDF)",
    "doc.aplicar": "⬛ Aplicar redacción…",
    "doc.terminar": "✖ Terminar",
    "doc.terminar_ayuda": "Borrar este documento de la memoria",
    "doc.terminar_confirmar": "Se borrará este documento de la memoria del servidor. ¿Continuar?",
    "det.titulo": "Datos detectados",
    "det.todas": "todas",
    "det.ninguna": "ninguna",
    "det.nota": "Revisa la lista: desmarca lo que NO quieras redactar. Nada se aplica sin tu confirmación.",
    "det.anadir_ph": "Añadir texto no detectado…",
    "det.vacio": "No se ha detectado ningún dato personal con los interruptores actuales.",
    "det.pagina": "Página {n}",
    "det.anadidos": "Añadidos a mano",
    "det.texto_manual": "texto manual",
    "det.zona_manual": "zona manual",
    "det.zonas": "{n} zona(s) dibujada(s)",
    "det.zonas_ayuda": "Clic sobre la zona negra del documento para quitarla.",
    "det.quitar": "Quitar",
    "det.capa": "capa {n}",
    "det.capa_ayuda": "Capa 1: reglas · Capa 2: modelo de lenguaje · Capa 3: IA local",
    "det.incluir_excluir": "clic para incluir/excluir",
    "det.zona_quitar": "Zona manual (clic para quitarla)",

    // ── Avisos sobre el documento ───────────────────────────────────────
    "aviso.ocr": "🔎 <strong>Documento leído con OCR.</strong> {detalle} Revisa con atención: el OCR puede equivocarse o no leer algún dato (sobre todo correos y símbolos). Puedes marcar zonas a mano si hace falta.",
    "aviso.capa3_caida": "⚠️ <strong>La IA local (capa 3) está activada pero no respondió.</strong> Se ha analizado solo con las capas 1-2. Revisa el servidor en «⚙️ Ajustes de IA».",

    // ── Diálogo de redacción ────────────────────────────────────────────
    "red.titulo": "Aplicar redacción definitiva",
    "red.aviso": "Se van a redactar <strong>{n}</strong> de forma <strong>irreversible</strong> en una copia del documento (el original que subiste no se modifica).",
    "red.elementos": "{n} elemento",
    "red.elementos_plural": "{n} elementos",
    "red.nota": "El texto se elimina del archivo: no podrá recuperarse copiando, pegando ni quitando los rectángulos.",
    "red.nota_fechas": "Las fechas se sustituirán por fechas desplazadas un número aleatorio de días (se conservan el orden y los intervalos).",
    "red.nota_edad": "La edad exacta se sustituirá por su rango etario; la fecha de nacimiento se tacha siempre.",
    "red.cancelar": "Cancelar",
    "red.confirmar": "Sí, redactar",
    "red.nada": "No hay nada marcado para redactar.",
    "red.error": "No se pudo redactar:\n\n",
    "res.titulo": "✅ Documento anonimizado",
    "res.ok": "Se han redactado {n} elementos. La comprobación posterior no encontró restos del texto redactado en el archivo final.",
    "res.cerrar": "Cerrar",
    "res.auditoria": "📋 Informe de auditoría",
    "res.auditoria_ayuda": "Informe de qué se redactó y con qué configuración, sin los datos originales",
    "res.descargar": "⬇ Descargar documento anonimizado",
    "res.residuales": "🔍 La segunda pasada encontró posibles datos sin redactar:",
    "res.redactar_tambien": "redactar también",
    "res.anadido": "añadido ✓",
    "res.residuales_nota": "Si añades alguno, cierra este diálogo y vuelve a pulsar «Aplicar redacción» para generar el documento de nuevo.",

    // ── Diagnóstico e IA local ──────────────────────────────────────────
    "diag.titulo": "🖥️ Tu equipo y la IA local",
    "diag.comprobando": "Comprobando tu equipo…",
    "diag.error": "No se pudo comprobar el equipo.",
    "diag.sistema": "Sistema",
    "diag.procesador": "Procesador",
    "diag.memoria": "Memoria (RAM)",
    "diag.aceleracion": "Aceleración",
    "diag.nucleos": "núcleos",
    "diag.libres": "libres ahora",
    "diag.desconocida": "desconocida",
    "diag.copiar": "📋 Copiar comandos",
    "diag.copiado": "Comandos copiados al portapapeles.",
    "diag.siguiente": "Tras instalarlo, abre <strong>⚙️ Ajustes de IA</strong>, elige el servidor y pulsa <strong>Probar</strong>.",
    "ia.titulo": "⚙️ Ajustes de la IA local (capa 3)",
    "ia.intro": "Es <strong>opcional</strong>. Conecta un modelo de IA que corra en tu red (Ollama o LM Studio) para detectar datos que las reglas no ven. El texto se envía solo a ese equipo de tu red; nada sale a internet.",
    "ia.servidor": "Servidor detectado",
    "ia.buscar": "Volver a buscar servidores en la red",
    "ia.buscando": "Buscando…",
    "ia.sin_servidor": "— no se encontró ningún servidor —",
    "ia.direccion": "…o escribe la dirección",
    "ia.puertos": "Ollama usa el puerto 11434; LM Studio, el 1234.",
    "ia.modelo": "Modelo",
    "ia.probar": "Probar",
    "ia.probando": "Probando…",
    "ia.prueba_ok": "✅ Funciona ({ms} ms). El modelo respondió: «{respuesta}»",
    "ia.prueba_error": "❌ No se pudo probar la conexión.",
    "ia.activar": "<strong>Activar la capa 3</strong> al analizar (puede tardar más en documentos largos)",
    "ia.guardar": "Guardar",
    "ia.estado_off": "IA local: desactivada",
    "ia.estado_on": "IA local: activada ({modelo})",
    "ia.modelos": "{n} modelos",
  },

  en: {
    // ── Header and footer ───────────────────────────────────────────────
    "app.titulo_pagina": "AnoniPRO — Local document anonymisation",
    "app.subtitulo": "Local document anonymisation — no data ever leaves your computer",
    "app.pie": "100% local processing · Works offline · Documents are never written to disk",
    "app.autor": "Author: Dr José Ramón Alberto Alonso",
    "cabecera.detector": "Name detection model",
    "cabecera.ocr": "OCR status",
    "cabecera.tema": "Switch between light and dark mode",
    "cabecera.idioma": "Cambiar a español",

    // ── Sign in ─────────────────────────────────────────────────────────
    "login.instruccion": "Enter the access password.",
    "login.password": "Password",
    "login.entrar": "Sign in",
    "login.error": "Wrong password.",

    // ── Settings panel ──────────────────────────────────────────────────
    "panel.perfil": "Profile",
    "panel.guardar_perfil": "Save the current settings as a profile",
    "panel.que_se_detecta": "What gets detected and redacted",
    "panel.lista_negra": "Always redact these terms",
    "panel.lista_negra_ayuda": "Type anything you want removed that isn't detected automatically (a nickname, a property, an internal code…). One box per term.",
    "panel.lista_blanca": "Never redact these terms",
    "panel.lista_blanca_ayuda": "Words to keep even if they look like personal data (a medicine, for example). If the word appears stuck inside a larger detection, it is trimmed from it.",
    "panel.anadir_casilla": "＋ Add another box",
    "panel.termino_ph": "Type a term…",
    "panel.quitar_casilla": "Remove this box",
    "panel.fechas_edad": "Dates and age",
    "panel.fechas": "Dates in the document",
    "panel.fechas_ayuda": "«Shift» moves every date by the same random number of days: the order and the intervals between them are preserved without revealing the real dates.",
    "panel.fechas_tachar": "Black out (redact)",
    "panel.fechas_desplazar": "Shift (keeps the timeline)",
    "panel.edad": "Exact age",
    "panel.edad_ayuda": "«Age band» replaces the exact age with its range: «47 years» becomes «45-49 years». The date of birth is always blacked out.",
    "panel.edad_tachar": "Black out (redact)",
    "panel.edad_rango": "Replace with age band (45-49 years)",
    "panel.ia": "Advanced detection (local AI)",
    "panel.ia_ayuda": "Optional. Uses an AI model running on your own network to catch data the rules miss. Everything works without it.",
    "panel.comprobar_equipo": "🖥️ Check my computer",
    "panel.ajustes_ia": "⚙️ AI settings",
    "panel.reanalizar": "🔄 Analyse again with these settings",
    "panel.perfil_propio": "— custom settings —",
    "panel.perfil_nombre": "Profile name (the current switch settings):",

    // ── Upload area ─────────────────────────────────────────────────────
    "subir.arrastra": "Drag a document here",
    "subir.o": "or",
    "subir.elegir": "Choose file…",
    "subir.formatos": "PDF (with text or scanned), Word (.docx) or image (JPG, PNG, TIFF)",
    "subir.ocr_nota": "Scans and images are read with OCR on this very computer.",
    "subir.ttl": "The document is processed only here and is wiped from memory after {min} minutes.",
    "subir.analizando": "Analysing «{nombre}»…",
    "subir.en_cola": " ({n} queued)",
    "subir.ocr_lento": "\nIf it is scanned, OCR may take a while on long documents.",
    "subir.reanalizando": "Analysing again…",
    "subir.formato_no": "Unsupported format. Use PDF, Word (.docx) or an image (JPG, PNG, TIFF).",
    "subir.error": "The document could not be processed:\n\n",
    "subir.caducado": "The document expired from memory. Please upload it again.",
    "subir.quedan": "  ·  {n} left in queue",

    // ── Document and detections ─────────────────────────────────────────
    "doc.zona_manual": "✏️ Mark an area by hand",
    "doc.zona_manual_ayuda": "Draw a rectangle on the document to redact it (PDF only)",
    "doc.aplicar": "⬛ Apply redaction…",
    "doc.terminar": "✖ Finish",
    "doc.terminar_ayuda": "Wipe this document from memory",
    "doc.terminar_confirmar": "This document will be wiped from the server's memory. Continue?",
    "det.titulo": "Data found",
    "det.todas": "all",
    "det.ninguna": "none",
    "det.nota": "Review the list: untick anything you do NOT want redacted. Nothing is applied without your confirmation.",
    "det.anadir_ph": "Add text that wasn't detected…",
    "det.vacio": "No personal data found with the current switches.",
    "det.pagina": "Page {n}",
    "det.anadidos": "Added by hand",
    "det.texto_manual": "manual text",
    "det.zona_manual": "manual area",
    "det.zonas": "{n} area(s) drawn",
    "det.zonas_ayuda": "Click the black area on the document to remove it.",
    "det.quitar": "Remove",
    "det.capa": "layer {n}",
    "det.capa_ayuda": "Layer 1: rules · Layer 2: language model · Layer 3: local AI",
    "det.incluir_excluir": "click to include/exclude",
    "det.zona_quitar": "Manual area (click to remove it)",

    // ── Document notices ────────────────────────────────────────────────
    "aviso.ocr": "🔎 <strong>Document read with OCR.</strong> {detalle} Review it carefully: OCR can misread or miss data (especially e-mail addresses and symbols). You can mark areas by hand if needed.",
    "aviso.capa3_caida": "⚠️ <strong>The local AI (layer 3) is switched on but did not answer.</strong> The document was analysed with layers 1-2 only. Check the server under «⚙️ AI settings».",

    // ── Redaction dialog ────────────────────────────────────────────────
    "red.titulo": "Apply final redaction",
    "red.aviso": "<strong>{n}</strong> will be redacted <strong>irreversibly</strong> on a copy of the document (the file you uploaded is not modified).",
    "red.elementos": "{n} item",
    "red.elementos_plural": "{n} items",
    "red.nota": "The text is deleted from the file: it cannot be recovered by copying, pasting or removing the black boxes.",
    "red.nota_fechas": "Dates will be replaced by dates shifted a random number of days (order and intervals are preserved).",
    "red.nota_edad": "The exact age will be replaced by its age band; the date of birth is always blacked out.",
    "red.cancelar": "Cancel",
    "red.confirmar": "Yes, redact",
    "red.nada": "Nothing is ticked for redaction.",
    "red.error": "The document could not be redacted:\n\n",
    "res.titulo": "✅ Document anonymised",
    "res.ok": "{n} items were redacted. The follow-up check found no traces of the redacted text in the final file.",
    "res.cerrar": "Close",
    "res.auditoria": "📋 Audit report",
    "res.auditoria_ayuda": "A report of what was redacted and with which settings, without the original data",
    "res.descargar": "⬇ Download anonymised document",
    "res.residuales": "🔍 The second pass found possible data still in the clear:",
    "res.redactar_tambien": "redact this too",
    "res.anadido": "added ✓",
    "res.residuales_nota": "If you add any, close this dialog and press «Apply redaction» again to produce the document anew.",

    // ── Diagnostics and local AI ────────────────────────────────────────
    "diag.titulo": "🖥️ Your computer and the local AI",
    "diag.comprobando": "Checking your computer…",
    "diag.error": "The computer could not be checked.",
    "diag.sistema": "System",
    "diag.procesador": "Processor",
    "diag.memoria": "Memory (RAM)",
    "diag.aceleracion": "Acceleration",
    "diag.nucleos": "cores",
    "diag.libres": "free right now",
    "diag.desconocida": "unknown",
    "diag.copiar": "📋 Copy commands",
    "diag.copiado": "Commands copied to the clipboard.",
    "diag.siguiente": "Once installed, open <strong>⚙️ AI settings</strong>, pick the server and press <strong>Test</strong>.",
    "ia.titulo": "⚙️ Local AI settings (layer 3)",
    "ia.intro": "This is <strong>optional</strong>. Connect an AI model running on your own network (Ollama or LM Studio) to detect data the rules miss. The text is sent only to that computer on your network; nothing goes out to the internet.",
    "ia.servidor": "Server found",
    "ia.buscar": "Search the network again",
    "ia.buscando": "Searching…",
    "ia.sin_servidor": "— no server found —",
    "ia.direccion": "…or type the address",
    "ia.puertos": "Ollama uses port 11434; LM Studio, 1234.",
    "ia.modelo": "Model",
    "ia.probar": "Test",
    "ia.probando": "Testing…",
    "ia.prueba_ok": "✅ It works ({ms} ms). The model replied: «{respuesta}»",
    "ia.prueba_error": "❌ The connection could not be tested.",
    "ia.activar": "<strong>Switch on layer 3</strong> when analysing (may take longer on long documents)",
    "ia.guardar": "Save",
    "ia.estado_off": "Local AI: off",
    "ia.estado_on": "Local AI: on ({modelo})",
    "ia.modelos": "{n} models",
  },
};

// Nombres de los perfiles predefinidos (los que crea el usuario se guardan tal cual)
const PERFILES_TRADUCIDOS = {
  es: {
    todo: "Todo activado",
    clinico: "Documento clínico",
    publicacion: "Publicación científica",
    docencia: "Docencia",
    juridico: "Jurídico (contratos y escritos)",
    empresa: "Empresa y RR. HH.",
    facturas: "Facturas y contabilidad",
    personal: "Documento personal",
  },
  en: {
    todo: "Everything on",
    clinico: "Clinical document",
    publicacion: "Scientific publication",
    docencia: "Teaching",
    juridico: "Legal (contracts and filings)",
    empresa: "Company and HR",
    facturas: "Invoices and accounting",
    personal: "Personal document",
  },
};
